### ISSUE TITLE
libbpf fais to compile with gcc 8.3 after the last sync

### ISSUE THREAD

**Issue by mrc0mmand** [libbpf/libbpf#87]
After the latest sync in #85 libbpf fails to compile with gcc 8.3 in Debian containers:

```
make: Entering directory '/build/src'
mkdir -p ../build/staticobjs
gcc-8 -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c bpf.c -o ../build/staticobjs/bpf.o
gcc-8 -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c btf.c -o ../build/staticobjs/btf.o
gcc-8 -I. -I../include -I../include/uapi -g -O2 -Werror -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c libbpf.c -o ../build/staticobjs/libbpf.o
libbpf.c: In function 'libbpf_prog_type_by_name.part.29':
libbpf.c:4692:4: error: 'strncat' specified bound 118 equals destination size [-Werror=stringop-truncation]
    strncat(dst, name + section_names[i].len,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     sizeof(raw_tp_btf_name) - (dst - raw_tp_btf_name));
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libbpf.c:4692:4: error: 'strncat' specified bound 118 equals destination size [-Werror=stringop-overflow=]
cc1: all warnings being treated as errors
make: *** [Makefile:100: ../build/staticobjs/libbpf.o] Error 1
make: Leaving directory '/build/src'
```

**Comment by evverx** [comment]
I'm wondering if instead of [turning off the stringop warnings](https://github.com/libbpf/libbpf/commit/4d86cae4f09f3db67d6d0543f94546f85f7b2c38) maybe it would make sense to use functions that are supposed to handle binary data to make `libbpf` ASan and static analysis-friendly. Even though currently the library isn't tested as thoroughly as it could be, ASan (with `strict_string_checks` on) and Coverity will most likely complain about that as well.

**Comment by anakryiko** [comment]
https://github.com/libbpf/libbpf/pull/89 contains upstream fix for this issue.

stringop warnings so far were completely false positive, this is the first time it would have actually caught real issue, which is why I disabled them. getting rid of strncpy is an option, of course, and patches are welcome.
